services:
  app:
    image: ghcr.io/aonbit/ridex:${IMAGE_TAG:-latest}
    container_name: ridex
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: sh scripts/upgrade.sh
